# fly.toml
app = "trading-system"
primary_region = "nrt"  # Tokyo (한국과 가까운 리전)

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  DATABASE_PATH = "/data/trading_data.db"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "5s"

[mounts]
  source = "trading_data"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
